# Netlify configuration file

[build]
  base = "."
  command = "npm run build"
  publish = "build"
  functionsDirectory = "functions"

[[redirects]]
  from = "/category"
  to = "/.netlify/functions/category"
  status = 200

[[redirects]]
  from = "/products"
  to = "/.netlify/functions/product"
  status = 200

[[redirects]]
  from = "/goal"
  to = "/.netlify/functions/goal"
  status = 200

[[redirects]]
  from = "/data"
  to = "/.netlify/functions/data"
  status = 200

[[redirects]]
  from = "/graph"
  to = "/.netlify/functions/graph"
  status = 200

[[redirects]]
  from = "/dispatch"
  to = "/.netlify/functions/dispatch"
  status = 200

[[redirects]]
  from = "/export"
  to = "/.netlify/functions/export"
  status = 200

[[redirects]]
  from = "/users"
  to = "/.netlify/functions/users"
  status = 200

[[redirects]]
  from = "/users/login"
  to = "/.netlify/functions/users"
  status = 200