[build]
  command = "npm run build"  # Builds your React app
  publish = "build"          # Output directory for React build
  functions = "functions"    # Directory for Netlify Functions

  [[redirects]]
  from = "/category"
  to = "/.netlify/functions/category"
  status = 200
  
   [[redirects]]
  from = "/products"
  to = "/.netlify/functions/product"
  status = 200
  
 